---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: radar
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.10.0
  url: oci://ocharted.alexsaphir.com/skyhook-io.github.io/helm-charts/radar
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radar
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: *app

  values:
    fullnameOverride: *app

    rbac:
      traffic: true
      metrics: true
      podLogs: true
      additionalCrdGroups:
        - cilium.io
        - dragonflydb.io
        - policy
        - policy.networking.k8s.io
        - postgresql.cnpg.io
        - volsync.backube

    mcp:
      enabled: false

    traffic:
      prometheusUrl: http://vmsingle-victoria-metrics.observability.svc.cluster.local:8428

    httpRoute:
      enabled: true
      # noinspection KubernetesUnknownValues
      hostnames: [ 'radar.${DOMAIN_NAME}' ]
      parentRefs:
        - name: envoy
          namespace: envoy-system
