---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-metrics-crds
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.10.1
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-operator-crds
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app victoria-metrics-crds
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
