---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name calibre-scrapper
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: 'enabled'
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 18

  instances: 2
  enablePDB: false

  bootstrap:
    recovery:
      database: *name
      owner: *name
      source: source

  postgresql:
    parameters:
      max_slot_wal_keep_size: 10GB

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-store

  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: minio-store
          serverName: *name

  resources:
    requests:
      memory: '2Gi'
    limits:
      hugepages-2Mi: '512Mi'


  storage:
    size: 50Gi
    storageClass: openebs-hostpath

  managed:
    roles:
      - name: *name
        ensure: present
        login: true
        createdb: true

    services:
      disabledDefaultServices: [ 'ro', 'r' ]
      additional:
        - selectorType: ro
          serviceTemplate:
            metadata:
              name: calibre-scrapper-lb
              annotations:
                external-dns.alpha.kubernetes.io/hostname: calibre-scrapper.svc.talos.${DOMAIN_NAME}

            spec:
              type: LoadBalancer
              ipFamilyPolicy: PreferDualStack
              externalTrafficPolicy: Local
