---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: calibre-scrapper
  namespace: calibre-scrapper
spec:
  prune: true
  interval: 1h
  path: cluster/apps/dev/calibre-scrapper/app
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
