[files]
exclude = ['pyproject.toml', '*.lock', '.mise.toml']

[format.rules]
key-value-equals-sign-alignment = true
line-width                      = 120
string-quote-style              = 'single'
trailing-comment-alignment      = true
