---
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  talos:
    # renovate: datasource=custom.talos-factory depName=siderolabs/talos
    version: v1.14.2

  policy:
    rebootMode: powercycle

  silences:
    - matchers:
        - name: alertname
          value: ^(CephDaemonSlowOps|CephHealthWarning|CephMonDown|CephMonDownQuorumAtRisk|CephOSDDown|CephOSDDownHigh|CephOSDHostDown|CephSlowOps|KubeNodeEviction|KubeNodeNotReady|KubeNodeReadinessFlapping|KubeNodeUnreachable|TargetDown)$
          matchType: "=~"

  healthChecks:
    - description: All nodes must be Ready
      apiVersion: v1
      kind: Node
      expr: status.conditions.filter(c, c.type == 'Ready').all(c, c.status == 'True')

    - description: Ceph cluster must be healthy
      apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ['HEALTH_OK']

    - description: Snaphsot must be completed
      apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Snapshot
      expr: |-
        status.phase != 'Running'

    - description: Ensures no pvc are being restored
      apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Restore
      expr: |-
        !(status.phase in ['Resolving', 'Restoring'])

    - description: CNPG cluster must be healthy with all instances ready
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      expr: |-
        status.phase in ['Cluster in healthy state'] && status.readyInstances == object.spec.instances

    - description: Dragonfly must be ready
      apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      expr: |-
        status.phase in ['Ready'] && (!has(status.isRollingUpdate) || !status.isRollingUpdate)
