---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: slurm-cluster
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.1.1
  url: oci://ghcr.io/slinkyproject/charts/slurm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: slurm-cluster
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: slurm-cluster

  driftDetection:
    ignore:
      - paths: [ '/spec/replicas' ]
        target:
          group: slinky.slurm.net
          kind: NodeSet
          name: slurm-cluster-worker-slinky

  values:
    clusterName: 'talos-slurm'

    controller:
      persistence:
        storageClassName: ceph-block

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

    loginsets:
      slinky:
        enabled: true
        rootSshAuthorizedKeys: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHF3kflkI15MWtCp3FkXi2L19MsjNdQvQ7jKfWomFkvl SuperUser'

        service:
          metadata:
            annotations:
              external-dns.alpha.kubernetes.io/hostname: slurm.svc.talos.${DOMAIN_NAME}
