---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: planka
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: planka-secret
    template:
      data:
        SECRET_KEY: '{{ .PLANKA_SECRET_KEY }}'

        OIDC_CLIENT_ID: '{{ .PLANKA_OIDC_CLIENT_ID }}'
        OIDC_CLIENT_SECRET: '{{ .PLANKA_OIDC_CLIENT_SECRET }}'

        S3_ACCESS_KEY_ID: '{{ .PLANKA_S3_ACCESS_KEY_ID }}'
        S3_SECRET_ACCESS_KEY: '{{ .PLANKA_S3_SECRET_ACCESS_KEY }}'

  dataFrom:
    - extract:
        key: planka-home
