---
apiVersion: authelia.milas.dev/v1alpha2
kind: OIDCClient
metadata:
  name: planka-oidc
  annotations:
    authelia.milas.dev/oidc-provider: kube-auth/default
spec:
  description: Planka
  public: false
  authorization_policy: two_factor
  preconfigured_consent_duration: 1m

  scopes: [ 'openid', 'profile', 'groups', 'email' ]
  redirect_uris: [ 'https://planka.${DOMAIN_NAME}/oidc-callback' ]

  userinfo_signing_algorithm: none
  response_modes: [ 'fragment' ]

  token_endpoint:
    auth_method: client_secret_basic

  secret_ref:
    name: planka-secret
    fields:
      client_id: OIDC_CLIENT_ID
      client_secret: OIDC_CLIENT_SECRET
