---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: grafana-oauth-secret
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: 'kube-auth'

      data:
        AUTH_CLIENT_ID: 'grafana'
        AUTH_CLIENT_SECRET: '{{ .AUTH_CLIENT_SECRET }}'

  dataFrom:
    - extract:
        key: grafana
