---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-metrics
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana

  datasource:
    type: victoriametrics-metrics-datasource
    name: prometheus
    editable: true
    access: proxy
    isDefault: true
    url: http://vmsingle-victoria-metrics-cluster.observability.svc.cluster.local:8428

  plugins:
    - name: victoriametrics-metrics-datasource
      version: latest

    - name: grafana-clock-panel
      version: latest

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana

  datasource:
    type: alertmanager
    name: AlertManager
    editable: true
    access: proxy
    jsonData:
      implementation: prometheus
    url: http://vmalertmanager-victoria-metrics-cluster.observability.svc.cluster.local:9093

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-logs
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana

  datasource:
    type: victoriametrics-logs-datasource
    name: VictoriaLogs
    editable: true
    access: proxy
    url: http://victoria-logs-server.observability.svc.cluster.local:9428

  plugins:
    - name: victoriametrics-logs-datasource
      version: latest
