---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: unifi
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana

  parentFolderRef: observability

  title: unifi
