---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hoard
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: hoard-secret
    template:
      data:
        HOARD_ADMIN_USERNAME: '{{ .HOARD_ADMIN_USERNAME }}'
        HOARD_ADMIN_PASSWORD: '{{ .HOARD_ADMIN_PASSWORD }}'

  dataFrom:
    - extract:
        key: hoard
