---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valheim
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: valheim-secret
    template:
      data:
        PASSWORD: '{{ .PASSWORD }}'

  dataFrom:
    - extract:
        key: valheim
