---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: planka-prod
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: planka-prod
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: planka-prod

  values:
    controllers:
      planka:
        annotations:
          reloader.stakater.com/auto: 'true'

        containers:
          app:
            image:
              repository: ghcr.io/plankanban/planka
              tag: 2.1.0@sha256:32c919d9e65b0479d1bbf0e4fb8e00fb11403a5234242b9f5fc900e595c2e2ce

            envFrom:
              - secretRef:
                  name: planka-prod-secret

            env:
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: database-planka-prod
                    key: POSTGRES_URL
              BASE_URL:
                value: &BASE_URL '{{ printf "https://%s" (first .Values.route.app.hostnames) }}'
              REACT_APP_SERVER_BASE_URL:
                value: *BASE_URL

              TRUST_PROXY: 'true'

              OIDC_ENFORCED: 'true'
              OIDC_SCOPES: openid profile email
              OIDC_IGNORE_ROLES: 'true'


              SMTP_HOST: mailpit.kube-system.svc.cluster.local
              SMTP_PORT: 1025
              SMTP_SECURE: false
              SMTP_FROM: 'Planka <planka@domain.com>'

              S3_ENABLE: true
              S3_REGION: us-east-1
              S3_ENDPOINT: https://s3.${DOMAIN_NAME}
              S3_BUCKET: planka-prod
              S3_FORCE_PATH_STYLE: true

            probes:
              liveness: &probe
                type: HTTP
                path: /
              readiness: *probe

            resources:
              requests:
                cpu: 10m
                memory: 250Mi

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ 'ALL' ] }

    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        ports:
          http:
            port: 1337

    route:
      app:
        hostnames:
          - 'plan.${DOMAIN_NAME}'
        parentRefs:
          - name: envoy
            namespace: envoy-system

    persistence:
      tmp:
        type: emptyDir
      tmp-dir:
        type: emptyDir
        globalMounts:
          - path: /app/logs
            subPath: logs

          - path: /app/.tmp
            subPath: tmp
