---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kopiur
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.6.0
  url: oci://ghcr.io/home-operations/charts/kopiur
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kopiur
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app

  values:
    features:
      kopiaUi:
        enabled: true

    extraVolumes:
      - name: repo
        nfs:
          server: nas.hosts.alexsaphir.com
          path: /mnt/user/Kopiur
    extraVolumeMounts:
      - name: repo
        mountPath: /repo

    monitoring:
      dashboards:
        enabled: true
        grafanaOperator:
          enabled: true
          matchLabels:
            grafana.internal/instance: grafana
      prometheusRule:
        enabled: true
      serviceMonitor:
        enabled: true

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch

    resources:
      requests:
        cpu: 100m
      limits:
        memory: 2Gi
