---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actual
  - foundryvtt
  - homepage
  - homer
  - immich
  - kanidm
  # - kguardian
  - planka
  - radar
  - tandoor-recipes
  - vaultwarden
  - your-spotify
