---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: renovate-operator-secret
    template:
      data:
        client-secret: '{{ .gitlab_oidc_secret }}'
        session-secret: '{{ .session_secret }}'

        # key cache
        dragonfly-url: 'redis://dragonfly.database.svc.cluster.local:6379/5'

        # s3 storage
        access-key-id: '{{ .AWS_ACCESS_KEY_ID }}'
        secret-access-key: '{{ .AWS_SECRET_ACCESS_KEY }}'

  dataFrom:
    - extract:
        key: renovate-operator
    - extract:
        key: renovate-gitlab
