---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: renovate-operator-secret
    template:
      data:
        client-secret: '{{ .gitlab_oidc_secret }}'
        session-secret: '{{ .session_secret }}'
        dragonfly-url: 'redis://dragonfly.database.svc.cluster.local:6379/5'

  dataFrom:
    - extract:
        key: renovate-operator
