---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: renovate-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.12.1
  url: oci://ghcr.io/mogenius/helm-charts/renovate-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name renovate-operator
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: *name

  values:
    fullnameOverride: *name
    replicaCount: 3

    auth:
      oidc:
        enabled: true
        issuerUrl: https://gitlab.alexsaphir.com
        clientId: 3b606bbc31526e35cb039268231686d629519a4f50420226f6faf4580e0ee098
        existingSecret: &secret renovate-operator-secret
        secretKey: client-secret
        sessionSecretKey: session-secret
        redirectUrl: https://renovate.${DOMAIN_NAME}/auth/callback

    valkey:
      existingSecret: *secret
      existingSecretKey: 'dragonfly-url'

    rbac:
      ownNamespaceOnly: true

    webhook:
      enabled: true

    config:
      defaultJobBackoffLimit: 5
      deleteSuccessfulJobs: true

      logStorage:
        mode: memory
      forwardCacheToJobs: true

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

      dashboard:
        enabled: true
        grafanaDashboard:
          allowCrossNamespaceImport: true
          instanceSelector:
            matchLabels:
              grafana.internal/instance: grafana
