---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: renovate-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 6.2.0
  url: oci://ghcr.io/mogenius/helm-charts/renovate-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name renovate-operator
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: *name

  values:
    fullnameOverride: *name
    replicaCount: 3

    policy:
      enabled: true

      allowedHosts:
        # keep the defaults you use
        - api.github.com
        - github.com
        # self-hosted
        - gitlab.alexsaphir.com
        - renovate.${DOMAIN_NAME}
        # in2p3
        - gitlab.in2p3.fr
      allowedImages:
        - ghcr.io/renovatebot/renovate

    # who you are
    auth:
      oidc:
        enabled: true
        issuerUrl: https://gitlab.alexsaphir.com
        clientId: 3b606bbc31526e35cb039268231686d629519a4f50420226f6faf4580e0ee098
        existingSecret: &secret renovate-operator-secret
        secretKey: client-secret
        sessionSecretKey: session-secret
        redirectUrl: https://renovate.${DOMAIN_NAME}/auth/callback

    # what you may do
    authorization:
      enabled: true
      defaults:
        readerGroups: [ ]
        adminGroups: [ ]

        readerUsers: [ ]
        adminUsers: [ Alexsaphir ]

        anonymousRead: true
        anonymousReadLogs: false

    externalKeyValueStore:
      existingSecret:
        name: *secret
        urlKey: dragonfly-url

    s3:
      bucket: renovate

      region: us-east-1
      endpoint: https://s3.alexsaphir.com
      forcePathStyle: true
      # -- Object key prefix used by the operator log store (LOG_STORE_MODE=s3)
      logPrefix: 'logs'
      # -- Object key prefix forwarded to Renovate jobs as RENOVATE_S3_URL
      cachePrefix: 'cache-operator'

      existingSecret: *secret

    rbac:
      ownNamespaceOnly: true

    webhook:
      enabled: true
      baseUrl: 'https://renovate.${DOMAIN_NAME}'


    config:
      defaultJobBackoffLimit: 5
      deleteSuccessfulJobs: true

      logStorage:
        mode: s3
      forwardCacheToJobs: true
      forwardS3CacheToJobs: true

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

      dashboard:
        enabled: true
        grafanaDashboard:
          allowCrossNamespaceImport: true
          instanceSelector:
            matchLabels:
              grafana.internal/instance: grafana
