---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab-minerva
components:
  - ../../../components/namespace
  - ../../../components/kopiur/secret
replacements:
  - path: ../../../components/replacements/ks.yaml
resources:
  - app/ks.yaml
patches:
  - target:
      kind: Namespace
    patch: |
      - op: add
        path: /metadata/annotations/kopiur.home-operations.com~1privileged-movers
        value: 'true'
