---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ocharted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: ocharted-secret
    template:
      data:
        auth: '{{ .OCHARTED_USERNAME }}:{{ .OCHARTED_PASSWORD }}'
  dataFrom:
    - extract:
        key: ocharted
