---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name gitlab-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 5m
  target:
    name: *name
    template:
      templateFrom:
        - target: Data
          configMap:
            name: gitlab-config-tpl
            items:
              - key: config.rb
                templateAs: Values

  dataFrom:
    - extract:
        key: gitlab-minerva
    - extract:
        key: minio

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: gitlab-oauth-secret
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: 'kube-auth'

      data:
        GITLAB_OAUTH_ID: '{{ .GITLAB_OAUTH_ID }}'
        GITLAB_OAUTH_SECRET: '{{ .GITLAB_OAUTH_SECRET }}'

  dataFrom:
    - extract:
        key: gitlab-minerva
