---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: &name observability-kubernetes
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana

  parentFolderUID: dfk427h43u3ggc

  uid: *name
  title: kubernetes
