---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotosocial
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: gotosocial-secret
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: 'kube-auth'

      data:
        GTS_OIDC_CLIENT_ID: '{{ .GTS_OIDC_CLIENT_ID }}'
        GTS_OIDC_CLIENT_SECRET: '{{ .GTS_OIDC_CLIENT_SECRET }}'

  dataFrom:
    - extract:
        key: gotosocial
