---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: litellm-secret
    template:
      data:
        LITELLM_MASTER_KEY: '{{ .LITELLM_MASTER_KEY }}' # Must start with sk-

  dataFrom:
    - extract:
        key: litellm
