---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tofu-controller
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.16.0-rc.7
  url: oci://ghcr.io/flux-iac/charts/tofu-controller
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tofu-controller

  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

  values:
    runner:
      image:
        repository: ghcr.io/home-operations/opentofu-runner
        tag: 1.11.7@sha256:7845404382f0922902e2667bd60e36872caa02ccd00855c5d6ac48721e9939f4

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
