---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: rustfs-secret
    template:
      data:
        RUSTFS_ACCESS_KEY: '{{ .MINIO_ROOT_USER }}'
        RUSTFS_SECRET_KEY: '{{ .MINIO_ROOT_PASSWORD }}'

  dataFrom:
    - extract:
        key: minio
