---
version: '3'

tasks:
  cnpg:backup:
    cmd: |
      kubectl get clusters.postgresql.cnpg.io --no-headers -A | while read -r ns name _; do \
          kubectl cnpg backup -n "$ns" "$name" --method=plugin --plugin-name=barman-cloud.cloudnative-pg.io; \
      done
    preconditions:
      - which kubectl
