---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-k3s
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: sonarr-k3s-secret
    template:
      data:
        SONARR__AUTH__APIKEY: '{{ .SONARR_API_KEY }}'

  dataFrom:
    - extract:
        key: sonarr
