---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanidm-mail
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: kanidm-mail-secret
    template:
      data:
        username: ''
        password: ''

  dataFrom:
    - extract:
        key: kanidm
