---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app seerr
  namespace: media
spec:
  components:
    - ../../../components/kopiur/backup

  postBuild:
    substitute:
      APP: *app
      PVC_NAME: seer
      KOPIUR_CAPACITY: 5Gi

  prune: true
  interval: 1h
  path: cluster/apps/media/seerr
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
