---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: nas
spec:
  allowedNamespaces:
    all: true

  backend:
    filesystem:
      path: /repo
      volume:
        nfs:
          server: nas.hosts.alexsaphir.com
          path: /mnt/user/Kopiur

  encryption:
    passwordSecretRef:
      name: kopiur-nas-secret
      namespace: kopiur-system
      key: KOPIA_PASSWORD

  moverDefaults:
    cache:
      capacity: 1Mi
      mode: Ephemeral
      storageClassName: openebs-hostpath

    podSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch

    scratch:
      capacity: 1Mi
      storageClassName: openebs-hostpath

    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    ttlSecondsAfterFinished: 300

  scheduleDefaults:
    timezone: '${TIMEZONE}'
