---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: nas
spec:
  allowedNamespaces:
    all: true

  backend:
    filesystem:
      path: /repo
      volume:
        nfs:
          server: nas.hosts.alexsaphir.com
          path: /mnt/user/Kopiur

  encryption:
    passwordSecretRef:
      name: kopiur-repository-secret
      namespace: kopiur-system
      key: KOPIA_PASSWORD

  scheduleDefaults:
    timezone: '${TIMEZONE}'

  server:
    auth:
      insecure:
        acknowledgeInsecure: true
    namespace: kopiur-system
