---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name immich-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 5m
  target:
    name: *name
    template:
      templateFrom:
        - target: Data
          configMap:
            name: immich-config-tpl
            items:
              - key: immich-config.yaml
                templateAs: Values

  dataFrom:
    - extract:
        key: immich

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: immich-oauth-secret
    template:
      data:
        IMMICH_OAUTH_CLIENT_ID: '{{ .IMMICH_OAUTH_CLIENT_ID }}'
        IMMICH_OAUTH_CLIENT_SECRET: '{{ .IMMICH_OAUTH_CLIENT_SECRET }}'

  dataFrom:
    - extract:
        key: immich
