---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
  namespace: immich
spec:
  components:
    - ../../../../components/kopiur/backup

  postBuild:
    substitute:
      APP: *app

      PVC_NAME: *app
      KOPIUR_CAPACITY: 300Gi
      KOPIUR_STORAGECLASS: ceph-filesystem
      KOPIUR_ACCESSMODES: ReadWriteMany

      KOPIUR_SNAPSHOTCLASS: csi-ceph-filesystem
      KOPIUR_STAGING_STORAGECLASS: csi-ceph-filesystem-backingsnapshot
      KOPIUR_STAGING_ACCESSMODES: ReadOnlyMany

  prune: true
  interval: 1h
  path: cluster/apps/self-hosted/immich/app
  sourceRef:
    kind: GitRepository
    name: talos-kubernetes
    namespace: flux-system
