---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mcp-group.yaml
  - virtual-mcp-server.yaml
  - service.yaml

  # - http-route.yaml
  - mcp-config-oidc.yaml

  - mcp-telemetry.yaml
  - podmonitor.yaml
  - grafana-dashboard.yaml
