---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-gitlab-in2p3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: renovate-gitlab-in2p3-secret
    template:
      data:
        # tokens to reduce the impact of rate limits
        RENOVATE_GITHUB_COM_TOKEN: '{{ .RENOVATE_GITHUB_COM_TOKEN }}'
        DOCKER_HUB_USER: '{{ .DOCKER_HUB_USER }}'
        DOCKER_HUB_PASSWORD: '{{ .DOCKER_HUB_PASSWORD }}'

        # renovate bot
        RENOVATE_TOKEN: '{{ .RENOVATE_GITLAB_PAT }}'
        RENOVATE_GIT_AUTHOR: '{{ .RENOVATE_GIT_AUTHOR }}'
        RENOVATE_GIT_PRIVATE_KEY: '{{ .RENOVATE_GIT_PRIVATE_KEY }}'

        RENOVATE_PAGINATE_ALL: 'true'
  dataFrom:
    - extract:
        key: docker-hub
    - extract:
        key: renovate-gitlab
    - extract:
        key: gitlab-in2p3-bot

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-gitlab-in2p3-webhook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    name: renovate-gitlab-in2p3-webhook-secret
    template:
      data:
        webhook-token: '{{ .RENOVATE_WEBHOOK_GITLAB }}'

  dataFrom:
    - extract:
        key: renovate-gitlab

---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: gitlab-in2p3
spec:
  parallelism: 4
  schedule: '0 */2 * * *'
  image: ghcr.io/renovatebot/renovate:44.33.2

  provider:
    name: gitlab
    endpoint: https://gitlab.in2p3.fr/api/v4

  secretRef: renovate-gitlab-in2p3-secret
  extraEnv:
    - name: RENOVATE_CONFIG_FILE
      value: /config/config.js

    - name: RENOVATE_ONBOARDING_CONFIG
      valueFrom:
        configMapKeyRef:
          name: &renovate-config gitlab-renovate-config
          key: onboardingConfig

  extraVolumes:
    - name: *renovate-config
      configMap:
        name: *renovate-config
  extraVolumeMounts:
    - name: *renovate-config
      mountPath: /config/config.js
      subPath: config.js

  runtimeClassName: kata
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-gitlab-in2p3-webhook-secret
        key: webhook-token
