---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: phanpy
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.2.1
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app phanpy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app

  values:
    controllers:
      *app :
        containers:
          main:
            image:
              repository: ghcr.io/jjgadgets/phanpy
              tag: 2026.10.09.febb38d@sha256:25c0a0298884e5c8484180ccf17dd2177b7f13cf9936818ae2a1d134e6ce00c4

            env:
              PHANPY_WEBSITE: &hostname '{{ .Release.Name }}.${DOMAIN_NAME}'
              PHANPY_DEFAULT_INSTANCE: '${DOMAIN_NAME}'

            resources:
              requests:
                cpu: 10m
              # limits:
              #   memory: 512Mi

    service:
      main:
        controller: phanpy
        ports:
          http:
            port: 80
            targetPort: 8080

    route:
      app:
        hostnames: [ *hostname ]
        parentRefs:
          - name: envoy
            namespace: envoy-system
