---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: context7-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  target:
    template:
      data:
        token: '{{ .API_KEY }}'

  dataFrom:
    - extract:
        key: context7
