---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: context7-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  data:
    - secretKey: token
      remoteRef:
        key: context7
        property: api-key
